name: Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: automated_testing

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Verify environment variables
      run: |
        if [ -n "${{ secrets.LCPDELTA_PACKAGE_TEST_ENACT_USERNAME }}" ]; then echo "ENACT_USERNAME is set"; else echo "ENACT_USERNAME is not set"; fi
        if [ -n "${{ secrets.LCPDELTA_PACKAGE_TEST_ENACT_API_KEY }}" ]; then echo "ENACT_API_KEY is set"; else echo "ENACT_API_KEY is not set"; fi
        if [ -n "${{ secrets.LCPDELTA_PACKAGE_TEST_FLEXTRACK_USERNAME }}" ]; then echo "FLEXTRACK_USERNAME is set"; else echo "FLEXTRACK_USERNAME is not set"; fi
        if [ -n "${{ secrets.LCPDELTA_PACKAGE_TEST_FLEXTRACK_API_KEY }}" ]; then echo "FLEXTRACK_API_KEY is set"; else echo "FLEXTRACK_API_KEY is not set"; fi
    
    - name: Run tests
      env:
        LCPDELTA_PACKAGE_TEST_ENACT_USERNAME: ${{ secrets.LCPDELTA_PACKAGE_TEST_ENACT_USERNAME }}
        LCPDELTA_PACKAGE_TEST_ENACT_API_KEY: ${{ secrets.LCPDELTA_PACKAGE_TEST_ENACT_API_KEY }}
        LCPDELTA_PACKAGE_TEST_FLEXTRACK_USERNAME: ${{ secrets.LCPDELTA_PACKAGE_TEST_FLEXTRACK_USERNAME }}
        LCPDELTA_PACKAGE_TEST_FLEXTRACK_API_KEY: ${{ secrets.LCPDELTA_PACKAGE_TEST_FLEXTRACK_API_KEY }}
      run: pytest
