name: Lint
on: push

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.x
  
      - name: Install Ruff
        run: pip install ruff

      - name: Ruff lint check
        uses: jpetrucciani/ruff-check@main
        with: 
          flags: '--ignore F401 --ignore E722'
